#source 'https://github.com/CocoaPods/Specs.git'
#platform :ios, '9.0'
#use_frameworks!
#    pod 'Masonry'
#    pod 'IQKeyboardManager', '~> 6.5.5'
#    pod 'TYAlertController'
#    pod 'JSONModel', '~> 1.7.0'
#    pod 'SDWebImage', '~> 5.8.0'
#    pod 'MJRefresh', '~> 3.4.3'
#    pod 'AvoidCrash', '~> 2.3.0-beta'
#    pod 'pop', '~> 1.0.8'
    #    pod 'AMapLocation'
    #    pod 'AMap2DMap'
    #    pod 'AMapSearch'
#    pod 'GoogleMaps', '~> 3.8.0'
#    pod 'GooglePlaces', '~> 3.8.0'
#    pod 'FLAnimatedImage', '~> 1.0.12'
target ‘BlocBlinds’ do
end
target ‘ConnectorDemo’ do
    pod 'Masonry'
    pod 'IQKeyboardManager', '~> 6.5.5'
    pod 'TYAlertController'
    pod 'JSONModel', '~> 1.7.0'
    pod 'SDWebImage', '~> 5.8.0'
    pod 'MJRefresh', '~> 3.4.3'
    pod 'AvoidCrash', '~> 2.3.0-beta'
    pod 'pop', '~> 1.0.8'
#    pod 'AMapLocation'
#    pod 'AMap2DMap'
#    pod 'AMapSearch'
   #   pod 'GoogleMaps', '~> 3.8.0'
   # pod 'GooglePlaces', '~> 3.8.0'
    pod 'FLAnimatedImage', '~> 1.0.12'
   # pod 'GTSDK'
#    pod 'Firebase'
#    pod 'Firebase/Messaging'
end
